<nav class="navbar navbar-expand-lg menu">
	<div class="container">
	  <div class="navbar-nav">
	  	<a class="menuItem" href="/timeline">
	  		Home
	  	</a>

	  	<a class="menuItem" href="/sair">
	  		Sair
	  	</a>
			<img src="/img/twitter_logo.png" class="menuIco" />
	  </div>
	</div>
</nav>

<div class="container mt-5">
	<div class="row pt-2">
		
		<div class="col-md-3">

			<div class="perfil">
				<div class="perfilTopo">

				</div>

				<div class="perfilPainel">
					
					<div class="row mt-2 mb-2">
						<div class="col mb-2">
							<span class="perfilPainelNome"><?php echo $this->view->info_usuario['nome'] ?></span>
						</div>
					</div>

					<div class="row mb-2">

						<div class="col">
							<span class="perfilPainelItem">Tweets</span><br />
							<span class="perfilPainelItemValor"><?php echo $this->view->total_tweets['total_tweets'] ?></span>
						</div>

						<div class="col">
							<span class="perfilPainelItem">Seguindo</span><br />
							<span class="perfilPainelItemValor"><?php echo $this->view->total_seguindo['total_seguindo'] ?></span>
						</div>

						<div class="col">
							<span class="perfilPainelItem">Seguidores</span><br />
							<span class="perfilPainelItemValor"><?php print_r ($this->view->total_seguidores['total_seguindo'])?></span>
						</div>

					</div>

				</div>
			</div>

		</div>

		<div class="col-md-6">
			<div class="row mb-2">
				<div class="col tweetBox">
					<form method="post" action="/tweet" enctype="multipart/form-data">
						<textarea class="form-control" name="tweet" id="exampleFormControlTextarea1" rows="3"></textarea>
						<input type="file" name="arquivo" id="">

						<?php if (isset($_GET['img_erro']) && $_GET['img_erro'] == 'formatoInvalido') { ?>
							<p class="text-danger text-formted">Tipo de formato inválido!!! Por favor, adicione um png ou jpg.</p>
						<?php } ?>
						<?php if (isset($_GET['img_erro']) && $_GET['img_erro'] == 'tamanhoMaximoUltrapassado') { ?>
							<p class="text-danger text-formted">MAX: 2mb</p>
						<?php } ?>

						<div class="col mt-2 d-flex justify-content-end">
							
							<button type="submit"  class="btn btn-primary">Tweet</button>
						</div>

					</form>
				</div>
			</div>

			<?php foreach ($this->view->tweets as $key => $tweet) { ?>
			<div class="row tweet">
				<div class="col">
					<p><strong><?php echo $tweet['nome'] ?></strong> <span class="text text-muted">- <?php echo $tweet['data'] ?></span></p>
					<p><?php echo $tweet['tweet']?> </p>

					<?php if ($tweet['path_imagem'] != null  ) { ?>
						<img width="350px" src="<?php echo $tweet['path_imagem'] ?>" alt=""><br/>
						<a href="<?php echo $tweet['path_imagem']  ?>" target="_blank" rel="noopener noreferrer">Ver imagem -> </a>

					<?php } ?>

					<br />
					<?php if($tweet['id_usuario'] == $_SESSION['id']){ ?>
					<form method="post" action="\remover_tweet?id=<?php echo $tweet['id'] ?>">
						<div class="col d-flex justify-content-end">
							<button type="submit" class="btn btn-danger"><small>Remover</small></button>
						</div>
					</form>
					<?php } ?>

				</div>
			</div>
			<?php } ?>

		</div>


		<div class="col-md-3">
			<div class="quemSeguir">
				<span class="quemSeguirTitulo">Quem seguir</span><br />
				<hr />
				<a href="\quemSeguir" class="quemSeguirTxt">Procurar por pessoas conhecidas</a>
				<!-- <a href="/img/img.png">IMG </a> -->
			</div>
		</div>

	</div>
</div>