<nav class="navbar navbar-expand-lg menu">
	<div class="container">
	  <div class="navbar-nav">
	  	<a class="menuItem" href="/timeline">
	  		Home
	  	</a>

	  	<a class="menuItem" href="/sair">
	  		Sair
	  	</a>
			<img src="/img/twitter_logo.png" class="menuIco" />
	  </div>
	</div>
</nav>

<div class="container mt-5">
	<div class="row pt-2">
		
		<div class="col-md-3">
			<!-- <img width="255px" height="95px" src="<?//php echo $this->view->foto_perfil['foto_perfil'] ?>" alt=""> -->
			<div class="perfil">
					<form name="arquivo1" id="arquivo1" method="post" enctype="multipart/form-data" action="\foto_edit?id=<?php echo $_SESSION['id'] ?>" class="text-center" >
						<label for="arquivo"> 
							<i class="fa-solid fa-pen"></i>
						</label>
						<input type="file" name="arquivo" id="arquivo" value="SELECT">
					</form>
				<div class="text-center" style="margin-bottom: 15px;">
					<img id="foto_perfil" src="<?php echo $this->view->foto_perfil['foto_perfil'] ?>" style="width: 100; height: 100; border: 1px solid red; border-radius: 60px; padding:;">
				</div>
				
				<div class="perfilPainel">
					
					<div class="row mt-2 mb-2">
						<div class="col mb-2 text-center">
							<span class="perfilPainelNome"><?php echo $this->view->info_usuario['nome'] ?></span>
						</div>
					</div>

					<div class="row mb-2">

						<div class="col">
							<span class="perfilPainelItem">Tweets</span><br />
							<span id="tweets" class="perfilPainelItemValor"><?php echo $this->view->total_tweets['total_tweets'] ?></span>
						</div>

						<div class="col">
							<span class="perfilPainelItem">Seguindo</span><br />
							<span class="perfilPainelItemValor"><?php echo $this->view->total_seguindo['total_seguindo'] ?></span>
						</div>

						<div class="col">
							<span class="perfilPainelItem">Seguidores</span><br />
							<span class="perfilPainelItemValor"><?php print_r ($this->view->total_seguidores['total_seguindo'])?></span>
						</div>

					</div>

				</div>
			</div>

		</div>

		<div class="col-md-6">
			<div class="row mb-2">
				<div class="col tweetBox">
					<form name="arquivo2" id="arquivo2" method="post" action="/tweet" enctype="multipart/form-data">
					
						<textarea value='texto'  class="form-control" name="tweet" id="texto_tweet" rows="3"></textarea>
						
						<input type="file" name="img_post" id="img_post" value="arquivo2">

						<?php if (isset($_GET['img_erro']) && $_GET['img_erro'] == 'formatoInvalido') { ?>
							<p class="text-danger text-formted">Tipo de formato inválido!!! Por favor, adicione um png ou jpg.</p>
						<?php } ?>
						<?php if (isset($_GET['img_erro']) && $_GET['img_erro'] == 'tamanhoMaximoUltrapassado') { ?>
							<p class="text-danger text-formted">MAX: 2mb</p>
						<?php } ?>

						<div class="col mt-2 d-flex justify-content-end">
				
							<button type="submit" id="enviar_tweet"  class="btn btn-primary">Tweet</button>
						</div>

					</form>
				</div>
			</div>

			<span id="caixa_tweets">
			<?php foreach ($this->view->tweets as $key => $tweet) { ?>
			<div class="row tweet">
				<div class="col">
					<p>
						<!-- Foto do perfil --><img style="width: 50px; height: 50px; border-radius:25px;" src="<?php echo $tweet['foto_perfil'] ?>" alt="">

						<br><strong><?php echo $tweet['nome'] ?></strong><br> <span class="text text-muted">- <?php echo $tweet['data'] ?></span>
					</p>
					<p><?php echo $tweet['tweet'] ?> </p>
					<?php if ($tweet['path_imagem'] != null) { ?>
						<img width="200em" src="<?php echo $tweet['path_imagem'] ?>" alt=""><br/>
						<a href="<?php echo $tweet['path_imagem'] ?>" target="_blank" rel="noopener noreferrer">Ver imagem -> </a>

					<?php } ?>
						
					<br />
					<?php if ($tweet['id_usuario'] == $_SESSION['id']) { ?>
					
						<div class="col d-flex justify-content-end">
							<button id="remover" onclick="remover(<?php echo $tweet['id'] ?>)" type="button" class="btn btn-danger"><small>Remover</small></button>
						</div>

					<?php } ?>
						
				</div>
			</div>
			<?php } ?>
			</span>
			<div class="row">
				<nav aria-label="...">
					<ul class="pagination">

						<li class="page-item"><a class="page-link" href="?pagina=1">Primeira</a></li>

						<?php for ($i = 1; $i <= $this->view->total_paginas; $i++){ ?>
							<li class="page-item <?php echo $this->view->pagina_ativa == $i ? 'active' : ''
							 ?>">
							 <a class="page-link" href="?pagina=<?php echo $i ?>"><?php echo $i ?></a>
							</li>
						<?php } ?>

						<li class="page-item">
						<a class="page-link"  href="?pagina=<?php echo  $this->view->total_paginas?>">Última</a>
						</li>

					</ul>
				</nav>
			</div>
		</div>


		<div class="col-md-3">
			<div class="quemSeguir">
				<span class="quemSeguirTitulo">Quem seguir</span><br />
				<hr />
				<div id="caixa_seguir">
					
				
				</div>
					<!-- <a href="/img/img.png">IMG </a> -->
			</div>
		</div>

	</div>
</div>


<script>
	var cont = 0;
	$('#texto_tweet').emojioneArea({
		pickerPosition: 'bottom',
	});

	function quemSeguir(){
		var caixa = document.getElementById('caixa_seguir');
		$.ajax({
			url: "\\quemSeguir",
			method: 'GET',
			dataType: 'json',
			
		}).done(function(result){
			
			for(let i = 0; i < result.length; i++){
				let linha = document.createElement('div');
				linha.className = 'row mt-2 border'

				let coluna = document.createElement('div');


				let imagem = document.createElement('img');
				imagem.style.width = '3em'
				imagem.style.borderRadius = '30px'
				imagem.src = result[i]['foto_perfil']
				imagem.className = 'ml-2'
				
				

				let nome = document.createElement('span');
				nome.innerHTML = result[i]['nome']
				nome.className = 'ml-2'

				let div_botao = document.createElement('div')
				

				let botao = document.createElement('button')
				botao.innerHTML = 'Seguir'
				botao.style.float = 'left'
				botao.className = 'btn btn-success'

				caixa.appendChild(linha)
				linha.appendChild(coluna)
				coluna.appendChild(imagem)
				coluna.appendChild(nome)
				coluna.appendChild(botao)
				
				

			}
		})
	}




	document.getElementById('arquivo').onchange = function(e){
		var foto_perfil = document.getElementById('foto_perfil');
		quemSeguir()
		if(e.target.files != null && e.target.files.length != 0){
			var arquivo = e.target.files[0];
			console.log(arquivo)
			var fd = new FormData();

			fd.append("arquivo", arquivo);
			var ajax = new XMLHttpRequest();

			ajax.onreadystatechange = function(){
				if(ajax.readyState == 4 && ajax.status == 200){
					try{
					let path_img = JSON.parse(ajax.responseText);
					foto_perfil.src = path_img.foto_perfil;

					}catch($Error){
						alert('Formato não permitido')
					}
				}
			}

			ajax.open("POST",'\\foto_edit?id=<?php echo $_SESSION['id'] ?>',true)
			ajax.send(fd);
			
		}
	}

	$('#arquivo2').submit((e) =>{
		e.preventDefault()
		quemSeguir()

		let texto = document.getElementById('texto_tweet').value
		console.log(texto)
		let img = e.target[2].files[0]
		
		
		var fd = new FormData();


		fd.append("arquivo2", img);
		var ajax = new XMLHttpRequest();

		ajax.onreadystatechange = function(){
			if(ajax.readyState == 4 && ajax.status == 200){
				document.querySelector('.emojionearea-editor').innerHTML = ''	
				document.getElementById('arquivo2').reset()
				getInfo();
				getTweets();
			}
		}

		ajax.open("POST",'\\tweet?id=<?php echo $_SESSION['id'] ?>&tweet='+texto,true)
		ajax.send(fd);
	
	})


	function remover(id){
		$.ajax({
			url: "\\remover_tweet",
			method:'GET',
			dataType: 'json',
			data: {id: id}

		}).done(function(result){
			console.log(result);
		})

		getInfo();
		getTweets();
	}

	function getInfo(){
		$.ajax({
			url: '\\getInfoUserAJAX',
			method: 'GET',
			dataType: 'json',
			data: {id: <?php echo $_SESSION['id'] ?>}
		}).done(function(result){
		
			console.log(result)
			$('#tweets').html(result[0]['total_tweets'])

		})

	}




	
	function getTweets(){
		var caixa = document.getElementById("caixa_tweets")
		$.ajax({
        url: '\\getTweets',
        method: 'GET',
        dataType: 'json'
    }).done(function(result){
		cont++
		if(cont == 10){
			window.location.reload()
		}
        console.log(result);
		caixa.innerHTML = ''
		
		
		
        for(let i = 0; i < result.length; i++){
			let linha = document.createElement('div');
			linha.classList = 'row tweet'

			let coluna = document.createElement('div');
			coluna.classList = 'col'

			let paragrafo_1 = document.createElement('p');

			let imagem_perfil = document.createElement('img');
			imagem_perfil.style.width = '50px'
			imagem_perfil.style.height = '50px'
			imagem_perfil.style.borderRadius = '25px'
			imagem_perfil.src = result[i]['foto_perfil']

			let paragrafo_2 = document.createElement('p');
			paragrafo_2.innerHTML = result[i]['nome']
			paragrafo_2.style.fontWeight = 'bold'

			let data = document.createElement('p');
			data.className = 'text text-muted'
			data.innerHTML = result[i]['data']

			let tweet_paragrafo3 = document.createElement('p');
			tweet_paragrafo3.innerHTML = result[i]['tweet']

			let imagem_post = document.createElement('img');
			imagem_post.style.width = '14em'
			imagem_post.src = result[i]['path_imagem']

			let link_imagem= document.createElement('a');
			link_imagem.href = result[i]['path_imagem'];
			link_imagem.target = "_blank"
			link_imagem.rel = 'noopener noreferrer'
			link_imagem.innerHTML = '<br>Ver imagem ->'

			

			let div_botao = document.createElement('div');
			div_botao.className = 'col d-flex justify-content-end'


			let botao_remover = document.createElement('button');
			botao_remover.type = 'button'
			botao_remover.className = 'btn btn-danger'
			

			botao_remover.onclick = function() {
				remover(result[i]['id']);
			}
			botao_remover.innerHTML = '<small>REMOVER</small>'


			caixa.appendChild(linha)
			linha.appendChild(coluna)
			coluna.appendChild(paragrafo_1)
			paragrafo_1.appendChild(imagem_perfil)
			paragrafo_1.appendChild(paragrafo_2)
			paragrafo_1.appendChild(data)

			coluna.appendChild(tweet_paragrafo3)

			if(result[i]['path_imagem'] != null){
				coluna.appendChild(imagem_post)
				coluna.appendChild(link_imagem)
			}
			if(result[i]['id_usuario'] == <?php echo $_SESSION['id'] ?>){
				coluna.appendChild(div_botao)
				
				div_botao.appendChild(botao_remover)
			}



		}

		

    })


	}

	
	
/*
//<//?php foreach ($this->view->tweets as $key => $tweet) { ?>

$('#caixa_tweets').prepend(
	'<div class="row tweet" ><div class="col"> <p> <!-- Foto do perfil --><img style="width: 50px; height: 50px; border-radius:25px;" src="<?php echo $tweet['foto_perfil'] ?>" alt=""> <strong><?php echo $tweet['nome'] ?></strong> <span class="text text-muted">- <?php echo $tweet['data'] ?></span>  </p> <p><?php echo $tweet['tweet'] ?> </p> <?php if ($tweet['path_imagem'] != null) { ?> <img width="200em" src="<?php echo $tweet['path_imagem'] ?>" alt=""><br/> <a href="<?php echo $tweet['path_imagem'] ?>" target="_blank" rel="noopener noreferrer">Ver imagem -> </a> <?php } ?> <?php if ($tweet['id_usuario'] == $_SESSION['id']) { ?> <form method="post" action="\remover_tweet?id=<?php echo $tweet['id'] ?>"> <div class="col d-flex justify-content-end"> <button type="submit" class="btn btn-danger"><small>Remover</small></button> </div> </form> 	<?php } ?> </div></div></div></div>'
	
)

<//?php } ?>

*/


	/*
		document.getElementById('arquivo2').onchange = function(e){
		console.log(e.target.files[0])
		let texto = document.getElementById('texto_tweet').value
		if(e.target.files != null && e.target.files.length != 0){
			var arquivo = e.target.files[0];
			var fd = new FormData();

			fd.append("arquivo2", arquivo);
			var ajax = new XMLHttpRequest();

			ajax.onreadystatechange = function(){
				if(ajax.readyState == 4 && ajax.status == 200){
					alert(ajax.responseText)
				}
			}

			ajax.open("POST",'\\tweet?id=&tweet='+texto,true)
			ajax.send(fd);
			}
		}*/

	
	
</script>